backend:
  name: github
  repo: CodersBros/LosKayakos
  branch: master
  base_url: https://github-auth.krzychu.netlify.app
  publish_mode: editorial_workflow
media_folder: static/images
public_folder: ../../static/images/

collections:
  - name: 'about-us' # Used in routes, e.g., /admin/collections/blog
    label: 'About-Us' # Used in the UI
    folder: 'content/about-us' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: name
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about-us' }
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
