backend:
  name: github
  repo: CodersBros/Los-Kayakos
  branch: master
  publish_mode: editorial_workflow
media_folder: static/images
public_folder: ../../static/images/

collections:
  - name: 'about-us' # Used in routes, e.g., /admin/collections/blog
    label: 'About-Us' # Used in the UI
    folder: 'content/about-us' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: name
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about-us' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'contact' # Used in routes, e.g., /admin/collections/blog
    label: 'Contact' # Used in the UI
    folder: 'content/contact' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: name
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'contact' }
      - { label: 'Tytuł', name: 'title', widget: 'string' }
      - { label: 'Telefon', name: 'phone', widget: 'string' }
      - { label: 'E-mail', name: 'email', widget: 'string' }
      - { label: 'Lokalizacja', name: 'location', widget: 'string' }
  - name: 'company' # Used in routes, e.g., /admin/collections/blog
    label: 'Company' # Used in the UI
    folder: 'content/company' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: name
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'company' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Nip', name: 'nip', widget: 'string' }
      - { label: 'Bank Number', name: 'bank_number', widget: 'string' }
      - { label: 'National Business Registry Number', name: 'regon', widget: 'string' }
  - name: 'media' # Used in routes, e.g., /admin/collections/blog
    label: 'Media' # Used in the UI
    folder: 'content/media' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: name
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'media' }
      - { label: 'Facebook', name: 'fecebook', widget: 'string', hint: 'URL path' }
      - { label: 'Instagram', name: 'instagram', widget: 'string', hint: 'URL path' }
  - name: 'hero' # Used in routes, e.g., /admin/collections/blog
    label: 'Hero' # Used in the UI
    folder: 'content/hero' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: name
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'hero' }
      - { label: 'Intro', name: 'intro', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'hero-slider' # Used in routes, e.g., /admin/collections/blog
    label: 'Hero-Slider' # Used in the UI
    folder: 'content/hero-slider' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: name
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'hero-slider' }
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'hero_slider', name: 'hero_slider', widget: 'image' }
      - { label: 'hero_slider_alt', name: 'hero_slider_alt', widget: 'string' }
  - name: 'offer' # Used in routes, e.g., /admin/collections/blog
    label: 'Oferta' # Used in the UI
    folder: 'content/offer' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: name
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'offer' }
      - { label: 'Główny nagłówek', name: 'title', widget: 'string' }
      - { label: 'Zdjęcie', name: 'offer_picture', widget: 'image' }
      - { label: 'Nazwa zdjęcia', name: 'offer_picture_alt', widget: string }
      - { label: 'Krótki Opis', name: 'short_description', widget: string }
  - name: 'how-do-we-work' # Used in routes, e.g., /admin/collections/blog
    label: 'Jak działamy' # Used in the UI
    folder: 'content/how-do-we-work' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: name
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'work' }
      - { label: 'Numer Kroku', name: 'number_step', widget: 'string', valueType: 'int', min: 1, step: 1, default: 1 }
      - { label: 'Tytuł kroku', name: 'title', widget: 'string' }
      - { label: 'Zdjęcie', name: 'work_picture', widget: 'image' }
      - { label: 'Nazwa zdjęcia', name: 'work_picture_alt', widget: string }
      - { label: 'Krótki Opis', name: 'short_description', widget: string }
      - {
          label: 'Order',
          name: 'order',
          widget: 'number',
          required: false,
          valueType: 'int',
          min: 1,
          step: 1,
          default: 1,
        }
  - name: 'AboutUs' # Used in routes, e.g., /admin/collections/blog
    label: 'O nas' # Used in the UI
    folder: 'content/aboutus' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: name
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'aboutUs' }
      - { label: 'Tytuł', name: 'title', title: 'string' }
      - { label: 'Tytuł grafiki 1', name: 'title_graphic_1', widget: 'string' }
      - { label: 'Tytuł grafiki 2', name: 'title_graphic_2', widget: 'string' }
      - { label: 'Tytuł grafiki 3', name: 'title_graphic_3', widget: 'string' }
      - { label: 'Tytuł grafiki 4', name: 'title_graphic_4', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'offer-subpage' # Used in routes, e.g., /admin/collections/blog
    label: 'Podstrona Oferta' # Used in the UI
    folder: 'content/offer-subpage' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: name
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'offer-subpage' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'gallery-slider' # Used in routes, e.g., /admin/collections/blog
    label: 'Galeria-Slider' # Used in the UI
    folder: 'content/gallery-slider' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: name
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'gallery-slider' }
      - { label: 'Nazwa', name: 'name', widget: 'string' }
      - { label: 'Zdjęcie', name: 'hero_slider', widget: 'image' }
      - { label: 'Tytuł Zdjęcia', name: 'hero_slider_alt', widget: 'string' }
      - {
          label: 'Numer porządkowy',
          name: 'order',
          widget: 'number',
          required: false,
          valueType: 'int',
          min: 1,
          step: 1,
          default: 1,
        }
  - name: 'gallery-text' # Used in routes, e.g., /admin/collections/blog
    label: 'Podstrona Galeria' # Used in the UI
    folder: 'content/gallery-text' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: name
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'gallery-text' }
      - { label: 'Tytuł', name: 'title', widget: 'string' }
      - { label: 'Tekst', name: 'body', widget: 'markdown' }
  - name: 'contact-text' # Used in routes, e.g., /admin/collections/blog
    label: 'Podstrona Kontakt' # Used in the UI
    folder: 'content/contact-text' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: name
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'contact-text' }
      - { label: 'Tytuł', name: 'title', widget: 'string' }
      - { label: 'Tekst', name: 'body', widget: 'markdown' }

  - name: 'prices' # Used in routes, e.g., /admin/collections/blog
    label: 'Ceny' # Used in the UI
    folder: 'content/prices' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: name
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'prices' }
      - { label: 'ID ceny', name: 'price_id', widget: 'string' }
      - { label: 'Nazwa', name: 'name', widget: 'string' }
      - { label: 'Cena ', name: 'price', widget: 'number' }
      - {
          label: 'Nazwa ceny',
          name: 'name_price',
          widget: 'string',
          hint: 'wpisujemy nazwę ceny np. kajak(pn. - czw.)',
        }
  - name: 'prices-list' # Used in routes, e.g., /admin/collections/blog
    label: 'cennik' # Used in the UI
    folder: 'content/prices-list' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: name
    fields: # The fields for each document, usually in front matter
      - {
          label: 'Ceny',
          name: 'prices',
          widget: 'relation',
          collection: 'prices',
          searchFields: ['name'],
          valueField: 'price_id',
          displayFields: ['name', 'price_id'],
          multiple: true,
          hint: 'dodajemy z listy rozwijanej ceny które będą wchodzić w skład cennika',
        }
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'prices-list' }
      - { label: 'Nazwa', name: 'name', widget: 'string' }
      - { label: 'Tytuł cennika', name: 'title', widget: 'string', hint: 'np. Ceny wynajmu kajaków ' }
      - {
          label: 'Tytuł kolumny cennika 1',
          name: 'column_title_1',
          widget: 'string',
          required: false,
          hint: 'np. 1 - 2 dni',
        }
      - {
          label: 'Tytuł kolumny cennika 2',
          name: 'column_title_2',
          widget: 'string',
          required: false,
          hint: 'np. 3 - 5 dni jeżeli jest gwiazdka musimy ją dodać w tytule',
        }
      - { label: 'Gwiazdka', name: 'star', widget: 'string', required: false, hint: 'wpisujemy tekst do gwiazdki' }
